version: '3.0'
services:
  platform:
    image: platform:latest
    container_name: platform
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      V1_DATABASE_URL: postgresql://root:root@postgres:5432/platform_development?schema=public
      SYNC_CHAIN_DATABASE_URL: postgresql://root:root@sync_chain:5432/sync_chain_development?schema=public
      REDIS_URL: redis://default:redis@redis:6379       # Redis.
      PORT: 3000
    depends_on:
      - postgres
      - redis
      - sync_chain
    links:
      - postgres
      - redis
      - sync_chain
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: platform_development
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
  sync_chain:
    image: postgres:latest
    container_name: sync_chain
    volumes:
      - /tmp/postgres-data-sync-chain:/var/lib/postgresql/data
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sync_chain_development
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
