name: 📄Docs
description: File an issue with the documentation.
title: "[DOCS] <title>"
labels: ["documentation"]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing. Include examples and links.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen or see.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
