name: CI
on: [push]

env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/platform_test
    SYNC_CHAIN_DATABASE_URL: postgresql://postgres:postgres@localhost:5442/sync_chain_test
    NODE_ENV: dev
    SESSION_SECRET: secretKey
    INVITE_SECRET: secretInvite
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
    AWS_METADATA_BASE_URI: ${{ secrets.AWS_METADATA_BASE_URI }}
    AWS_IMAGE_BASE_URI: ${{ secrets.AWS_IMAGE_BASE_URI }}
    AWS_BASE_URL: ${{ secrets.AWS_BASE_URL }}
    COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
    YARN_IGNORE_NODE: 1

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest-m
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_PORT: 5432
                    POSTGRES_DB: platform_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

            postgres-sync-chain:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_PORT: 5432
                    POSTGRES_DB: sync_chain_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5442:5432
        steps:
            - uses: actions/checkout@v3

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.10.0
                  cache: 'yarn'

            - name: Set Yarn 3
              run: yarn set version 3

            - name: yarn install --immutable
              run: yarn install --immutable

            - name: Migrate Database
              run: yarn typeorm:schema:sync

            - name: Migrate Sync Chain Database
              run: yarn typeorm:schema:sync-chain:sync

            - name: Run Tests/CI
              env:
                  NODE_OPTIONS: '--max_old_space_size=8192'
              run: yarn test:ci
