name: Lint
on: [push]

env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/platform_test
    SYNC_CHAIN_DATABASE_URL: postgresql://postgres:postgres@localhost:5442/sync_chain_test
    NODE_ENV: dev
    SESSION_SECRET: secretKey
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
    AWS_METADATA_BASE_URI: ${{ secrets.AWS_METADATA_BASE_URI }}
    AWS_IMAGE_BASE_URI: ${{ secrets.AWS_IMAGE_BASE_URI }}
    AWS_BASE_URL: ${{ secrets.AWS_BASE_URL }}
    RPC_URL: https://goerli-rollup.arbitrum.io/rpc
    CHAIN_ID: 421613
    NETWORK: arbitrum
    KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    PROFILE_NFT_CONTRACT: '0x7961f5c879604dc0a291ff66efd3cab4ec2bcfc7'
    COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.10.0
                  cache: 'yarn'

            - name: Set Yarn 3
              run: yarn set version stable

            - name: yarn install --immutable
              run: yarn install --immutable

            - name: Lint
              run: yarn lint:ci
